server:
  port: 8080
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

build:
  version: "4.0.0"

accounts:
  message: "welcome to accounts testing management endpoints again changes for rabbit mqsd 12345 exposure eweb  prod microservices"
  contactDetails:
    name: "Prashant Pal prod"
    mobileNumber: "7310547955 prod"
    emal: "{cipher}d9ef5cf938b959a081965382a754ebaf280aeabdfdb6e76ecfaf8df7cb12c16c2e89af1e72fa6a4134e04b2b5b658f89"
  onCallSupport:
    - "9997865023 prod"
    - "8979296780 prod"
