spring:
  application:
    name: "apigateway"
  config:
    import: "optional:configserver:http://configserver:8071/"
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  data:
    redis:
      connect-timeout: 2s
      host: redis
      port: 6379

resilience4j:
  circuitbreaker:
    configs:
      default:
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
        slidingWindowSize: 10
server:
  port: 9091







