server:
  port: 9001
spring:
  application:
    name: cards
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_latest
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

build:
  version: "1.0.0"

cards:
  message: "welcome to cards applications"
  contactDetails:
    name: "Prashant Pal"
    mobileNumber: "7310547955"
    email: "palprashant18970@gmail.com"
  onCallSupport:
    - "8979296780"
    - "9997865023"