server:
  port: 9002
spring:
  application:
    name: loans
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_latest
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

build:
  version: "1.2.3"

loans:
  message: "welcome to loans applications"
  contactDetails:
    name: "Prashant Pal"
    email: "palprashant18970@gmail.com"
    mobileNumber: "7310547955"
  onCallSupport:
    - "8979296780"
    - "9667977871"